function draw_SS( mode )
% Init Viterbi Visualization
 
%  Auto-generated by MATLAB on 10-May-2005 20:13:55
 
%% Create figure
figure1 = figure('FileName','C:\Research\Matlab\ViterbiFigure.fig');
 
%% Create axes
axes1 = axes(...
  'Color',[0.9922 0.9176 0.7961],...
  'XGrid','on',...
  'XColor',[0.2 0.2 0.2], ...
  'XTick',[0 0.5 1 1.5 2],...
  'YTick',[-0.3 -0.1 0.1 0.3],...
  'YTickLabel',{'{2,2}','{2,1}','Onset','{2,2}'},...
  'Parent',figure1);
axis(axes1,[-0.5 3 -1 1]);
title(axes1,'Viterbi Algorithm at t=');
xlabel(axes1,'t');
ylabel(axes1,'{r(t), r(t-1)}');
box(axes1,'on');
hold(axes1,'all');
 
