function str = pot2str( p )
%DISPLAY Displays potential in command window

nl = sprintf('\n');

str = '';

for k=(1:length(p))
    
    str = ['Potential', nl, '---------', nl, ...
        ['mu =             ' num2str(p(k).mu')], nl, ...
        ['Sigma =          ' num2str(diag(p(k).Sigma)')],nl, ...
        ['2-slice Sigma =  ',num2str(diag(p(k).Sigma_2s)')], nl, ...
        ['p =              ',num2str(p(k).p)], nl, ...
        ['-LogLike =        ',num2str(p(k).LL)], nl, ...
        ['Likelihood =     ',num2str(p(k).Likelihood)], nl, ...
        ['Posterior =      ',num2str(p(k).Posterior)], nl, ...
        '---------', nl,nl, str ];
    
end